server:
  host: "0.0.0.0"
  port: 8080

langchain4j:
  open-ai:
    chat-model:
#      enabled: true
      api-key: "demo"
      model-name: "gpt-4o-mini"
  oracle-genai:
    chat-model:
      enabled: true
      compartment-id: "ocid1.tenancy.oc1..aaaaaaaaonou3anbsghdg723hfoodyj3y6gmx3kqma5dcou4n2fh2setk6ta"
      chat-model-id: "ocid1.generativeaimodel.oc1.eu-frankfurt-1.amaaaaaask7dceya4tdabclcsqbc3yj2mozvvqoq5ccmliv3354hfu3mx6bq"
  rag:
    embedding-store-content-retriever:
      enabled: true
      max-results: 10
      min-score: 0.6
      embedding-model: "@default"
      embedding-store: "@default"

app:
  root: "/home/daniel/idp/ora/helidon/helidon-4/docs/src/main/asciidoc"
  inclusions: "*.adoc"